create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text unique not null,
  password_hash text not null,
  must_change_password boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.cases (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null check (category in ('criminal', 'drugs')),
  subcategory text not null check (subcategory in ('arrest', 'release')),
  case_date timestamptz,
  created_by bigint not null references public.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.images (
  id bigint generated by default as identity primary key,
  case_id bigint not null references public.cases(id) on delete cascade,
  filename text not null,
  original_name text not null,
  mime_type text not null,
  size bigint not null,
  created_at timestamptz not null default now()
);
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id),
  action text not null,
  case_id bigint references public.cases(id) on delete set null,
  details text,
  created_at timestamptz not null default now()
);
create table if not exists public.sessions (
  token_hash text primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  expires_at bigint not null,
  created_at timestamptz not null default now()
);
create index if not exists idx_cases_name on public.cases(name);
create index if not exists idx_images_case on public.images(case_id);
create index if not exists idx_sessions_expiry on public.sessions(expires_at);
insert into storage.buckets (id, name, public)
values ('case-images', 'case-images', false)
on conflict (id) do nothing;